// indicators ported for serverless
function sma(values, period) { if (values.length < period) return null; return values.slice(-period).reduce((s,v)=>s+v,0)/period; }
function emaSeries(values, period) { if (!values.length) return []; const multiplier = 2/(period+1); const seed = values.slice(0,Math.min(period,values.length)).reduce((s,v)=>s+v,0)/Math.min(period,values.length); let previous = seed; return values.map((value,index)=>{ if (index < period-1) return null; previous = index===period-1?seed:(value-previous)*multiplier+previous; return previous; }); }
function ema(values,period){ return emaSeries(values,period).filter(Number.isFinite).at(-1) ?? null; }
function rsi(values, period=14){ if (values.length <= period) return null; const changes = values.slice(-period-1).map((v,i,list)=> i? v - list[i-1] : null).slice(1); const gains = changes.map(c=>Math.max(c,0)); const losses = changes.map(c=>Math.max(-c,0)); const avgG = gains.reduce((s,v)=>s+v,0)/period; const avgL = losses.reduce((s,v)=>s+v,0)/period; return avgL===0?100:100-100/(1+avgG/avgL); }
function macd(values, fast=12, slow=26, signal=9){ if (values.length < slow + signal) return null; const fastS = emaSeries(values, fast); const slowS = emaSeries(values, slow); const line = values.map((_,i)=> Number.isFinite(fastS[i]) && Number.isFinite(slowS[i]) ? fastS[i] - slowS[i] : null); const valid = line.filter(Number.isFinite); const signalLine = ema(valid, signal); const macdLine = valid.at(-1); return { line: macdLine, signal: signalLine, histogram: macdLine - signalLine }; }
function adx(candles, period=14){ if (candles.length < period+1) return null; const slice = candles.slice(-period-1); let plus=0, minus=0, tr=0; for(let i=1;i<slice.length;i++){ const up = slice[i].high - slice[i-1].high; const down = slice[i-1].low - slice[i].low; plus += up>down && up>0? up:0; minus += down>up && down>0? down:0; tr += Math.max(slice[i].high - slice[i].low, Math.abs(slice[i].high - slice[i-1].close), Math.abs(slice[i].low - slice[i-1].close)); } if (!tr) return 0; const pdi = 100*plus/tr; const mdi = 100*minus/tr; return 100 * Math.abs(pdi-mdi) / (pdi + mdi || 1); }
function bollinger(values, period=20, deviations=2){ const middle = sma(values, period); if (middle === null) return null; const variance = values.slice(-period).reduce((s,v)=> s + (v-middle)**2,0)/period; const sd = Math.sqrt(variance); return { upper: middle + deviations*sd, middle, lower: middle - deviations*sd }; }
function vwap(candles){ const totals = candles.reduce((acc,c)=> ({ pv: acc.pv + ((c.high + c.low + c.close)/3) * c.volume, volume: acc.volume + c.volume }), { pv:0, volume:0 }); return totals.volume? totals.pv / totals.volume : null; }
function momentum(values, period=10){ return values.length > period ? ((values.at(-1) / values.at(-period-1)) - 1) * 100 : null; }
module.exports = { sma, ema, rsi, macd, adx, bollinger, vwap, momentum, emaSeries };
